apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: default
  labels:
    app: app1
spec:
  selector:
      matchLabels:
        app: app1
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: app1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082


  
 
